services:
  - type: web
    name: portfolio-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: MonApi
      - key: Jwt__Audience
        value: MonApiUsers
      - key: Smtp__Host
        sync: false
      - key: Smtp__Port
        sync: false
      - key: Smtp__From
        sync: false
      - key: Smtp__User
        sync: false
      - key: Smtp__Password
        sync: false
      - key: Smtp__NotificationRecipient
        sync: false
      - key: Cors__AllowedOrigins__0
        value: https://portfolio-qehavw5bz-vessah14-1878s-projects.vercel.app
      - key: Cors__AllowedOrigins__1
        value: http://localhost:3000
      - key: Cors__AllowedOrigins__2
        value: https://admin-qehavw5bz-vessah14-1878s-projects.vercel.app
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
