services:
  - type: web
    name: portfolio-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: MonApi
      - key: Jwt__Audience
        value: MonApiUsers
      - key: Smtp__Host
        sync: false
      - key: Smtp__Port
        sync: false
      - key: Smtp__From
        sync: false
      - key: Smtp__User
        sync: false
      - key: Smtp__Password
        sync: false
      - key: Smtp__NotificationRecipient
        sync: false
      - key: Cors__AllowedOrigins__0
        value: https://frontend-wheat-two-hh3yzglt50.vercel.app
      - key: Cors__AllowedOrigins__1
        value: https://admin-amber-six-49.vercel.app
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
      - key: AdminSeed__Enabled
        value: "true"
      - key: AdminSeed__Nom
        value: VNAtech
      - key: AdminSeed__Prenom
        value: Administrateur
      - key: AdminSeed__Email
        value: admin@vnatech.com
      - key: AdminSeed__Password
        sync: false
